branches:
  only:
  - master
  - scala-2.9
  - scala-2.10
language: scala
jdk:
- openjdk6
#- openjdk7
#- oraclejdk7
#- oraclejdk8
scala:
- 2.11.2
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y openjdk-6-source
install:
- ./.travis-cache.sh
script:
- sbt ++$TRAVIS_SCALA_VERSION clean test
- ./.check-diff.sh
# FIXME: https://github.com/ensime/ensime-server/issues/597
#- sbt ++$TRAVIS_SCALA_VERSION clean scoverage:test
after_success:
# FIXME: blocked on https://github.com/scoverage/sbt-coveralls/issues/21
#- sbt ++$TRAVIS_SCALA_VERSION coveralls
- sbt ++$TRAVIS_SCALA_VERSION clean $(if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$JAVA_HOME" == "$(jdk_switcher home openjdk6)" ]]; then echo "publish"; fi)
env:
  global:
    # travis encrypt -r ensime/ensime-server SONATYPE_USERNAME=<USERNAME>
    # travis encrypt -r ensime/ensime-server SONATYPE_PASSWORD=<PASSWORD>
    - secure: "IqDHZwYDAdif+BAJ0u57Ci7UEp4k0y8D+uDh51g6FqAIybD1HZ6TINojwj79675mjFaA9szXARkGAEuPfQ57tpC8Bevaj0zKX64TBE3HEdzuQL3i7dxi13DFEmCsUFeS7zqSMsqFcz5a6yASRujttDt2x0GCakOp82TvgI4NANM="
    - secure: "R90/HAOWcNEcs7CLx0ID/qLKBS9EC8Z52c9EPsmIx7dTWXGAOmbj7klUbWjkMsa/SkDYrfBTSPPsdW2QBY66pU8NeqL2YiguKNTVrOoFclEj/kfejQqJcII1PwwSBhVBXhp+bQ+ZHHe8MySDehK7hedL1fNzc8+RpLSUe2ROd90="
